---
title: "bootstrap_method"
author: "Ningning Long"
date: "November 19, 2016"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


Bootstrap
```{r}
#create a mfa object with mfa function
mymfa <- mfa(wines, sets, ncomps = 2, T, scaling_vec)




#Description: bootstrap method for mfa
#
# Arguments:
#   mfa: a list, the mfa object created by the mfa function
#   value: a integer, the number of times of bootstrap
#
# Returns: a list, containing the mean, standard deviation and bootstrap
#          ratio of the bootstrap
"bootstrap"<- function(mfa,value) UseMethod("bootstrap")
"bootstrap.mfa" <- function(mfa,value){
  
  f_list <- list()
  n_table <- length(mfa$partial_factor_scores)
  
  #sampling and get the list of bootstrapped factor scores from each sample
  for(i in 1:value){
    b <- sample(1:n_table, n_table,replace = TRUE)
    sum <- matrix(0,nrow(mfa$partial_factor_scores[[1]]),
                  ncol(mfa$partial_factor_scores[[1]]))
    for (j in b){
        sum = sum + mfa$partial_factor_scores[[j]]
    }
    f = sum/n_table
    f_list[[i]] <- f
  }
  
  
  #calculate the mean of bootstrap samples
  sample_mean <- Reduce("+",f_list)/value
  
  
  #calculate the sd of bootstrap samples
  difference_square <- list()
  for (i in 1:value){
    difference_square[[i]]<-(f_list[[i]]-sample_mean)*(f_list[[i]]-sample_mean)
  }
  sample_variance <- Reduce("+",difference_square)/value
  
  
  #calculate the bootstrap ratio
  t_star <- sample_mean/sqrt(sample_variance)
  
  #create output list
  output <- list(sample_mean, sqrt(sample_variance), t_star)
  names(output) <- c("mean", "sd", "bootstrap_ratio")
  
  return(output)
}



  


#Description: method of ploting bootstrap ratio  
#
# Arguments:
#   mfa: a list, the mfa object created by the mfa function
#   value: a integer, the number of times of bootstrap
#
# Returns: a list, containing the mean, standard deviation and bootstrap
#          ratio of the bootstrap; Also, the plots of bootstrap ratio for
#          each dimension
"plot_bootstrap"<- function(mfa,value) UseMethod("plot_bootstrap")
"plot_bootstrap.mfa" <- function(mfa,value){
  
  #bootstrap from the input mfa with input size (value)
  out <- bootstrap(mfa,value)
  
  #get the dimension of the input mfa
  dimension <- ncol(mfa$partial_factor_scores[[1]])
  
  #par(mfrow=c(dimension,1)) (without it, I can plot in different pages)
  #plot the bootstrap ratio for each dimension
  for(i in 1:dimension){
      par(xpd=F)
      barplot(out$bootstrap_ratio[,i],main = "Bootstrap Ratio Plot", 
            xlab = paste("Dimension",i,sep = ""), ylab = "Bootstrap Ratio",
            names.arg = mfa$observation_names, horiz = TRUE)
      abline(v=0)
      abline(v=-3)
      abline(v=3)
  }
  
  #except for returning the plots, also return the bootstrap result
  return(out)
}



bootstrap(mymfa,1000)
plot_bootstrap(mymfa,1000)
```